FROM mhart/alpine-node:10 AS build

WORKDIR /usr/src/app
COPY package.json .
RUN yarn
COPY . .
RUN yarn build

# final app
FROM mhart/alpine-node:10
WORKDIR /usr/src/app
COPY --from=build /usr/src/app .

CMD ["yarn", "dev"]
