# build and compile stage
FROM mhart/alpine-node:10 AS build

WORKDIR /usr/src/api
COPY package.json .
RUN yarn
COPY . .

# final app
FROM mhart/alpine-node:slim-10
WORKDIR /usr/src/api
COPY --from=build /usr/src/api .

CMD ["node", "."]
